stages: 
  - install 

install_package:
  stage: install
  image: python:latest  
  script: 
    - apt-get -y update && apt-get install git -y
    - pip install --upgrade pip 
    - pip install --prefer-binary .
  tags:
    - svom-specific
