name: gammagwfollowup
channels:
  - default
  - cta-observatory
  - conda-forge
dependencies:
  - python=3.6
  - gammapy=0.9
  - astropy==4.1
  - ipython
  - numpy
  - pip
  - pip:
      - MOCpy
      - pytz
      - healpy