name: gammagwfollowup
channels:
  - default
  - cta-observatory
  - conda-forge
dependencies:
  - python=3.6
  - astropy==4.1
  - ipython
  - numpy==1.19.5
  - pip
  - pip:
      - MOCpy
      - pytz
      - healpy